name: AuraTech Agency CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup PHP CLI Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Scan PHP Syntax Errors
        run: |
          find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \;

      - name: Validate Dockerfile Build
        run: |
          docker build -t auratech-web-test:latest .

  deploy:
    name: 🎉 Deploy to InfinityFree
    runs-on: ubuntu-latest
    needs: build-and-test # سحر الـ DevOps: الرفع لن يبدأ إلا إذا نجح فحص الدوكر والـ PHP وتأكدنا أن كودك سليم 100%!
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
    
      - name: 📂 Sync files to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /htdocs/
          clean: true